use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated_dir = out_dir.join("flatbuffers_generated");
    fs::create_dir_all(&generated_dir).unwrap();

    let flatc = match find_flatc() {
        Some(path) => path,
        None => {
            // Per design document Section 5.7: "missing flatc must cause the build
            // to explicitly fail, not silently generate empty modules"
            panic!(
                "flatc not found. The FlatBuffers compiler is required for build.\n\
                 Install it with:\n  brew install flatbuffers\n  # or: apt install flatbuffers-compiler\n  # or: set FLATC=/path/to/flatc"
            );
        }
    };

    let fbs_dir = find_fbs_dir();

    let fbs_files: Vec<PathBuf> = fs::read_dir(&fbs_dir)
        .expect("Failed to read fbs directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "fbs"))
        // Only include schemas compatible with flatc --rust
        // Others use "vectors of unions" which Rust codegen doesn't support yet
        // (cypher.fbs, snapshot.fbs, standingquery.fbs, standingquerystates.fbs)
        .filter(|p| {
            let name = p.file_name().unwrap().to_string_lossy();
            matches!(
                name.as_ref(),
                "base.fbs" | "journal.fbs" | "domainindexevent.fbs" | "wal_record.fbs"
            )
        })
        .collect();

    if fbs_files.is_empty() {
        panic!("No .fbs files found in {}", fbs_dir.display());
    }

    println!("cargo:rerun-if-changed={}", fbs_dir.display());
    for fbs_file in &fbs_files {
        println!("cargo:rerun-if-changed={}", fbs_file.display());
    }

    // Generate Rust code from FlatBuffers schemas
    // Use --rust-module-root-file to generate a single combined file
    // This avoids cross-module import issues with the generated code
    let status = Command::new(&flatc)
        .arg("--rust")
        .arg("--rust-module-root-file")
        .arg("-I")
        .arg(&fbs_dir)
        .arg("-o")
        .arg(&generated_dir)
        .args(&fbs_files)
        .status()
        .expect("Failed to run flatc");

    if !status.success() {
        panic!("flatc failed with status: {status}");
    }

    // The generated mod.rs from flatc includes all modules
    // Let's also create a wrapper that re-exports everything
    let mod_rs = generated_dir.join("mod.rs");
    if !mod_rs.exists() {
        // If flatc didn't generate mod.rs, create one
        let mut content =
            String::from("// Auto-generated by build.rs from FlatBuffers schemas\n\n");
        content.push_str("#[allow(unused_imports, dead_code, clippy::all)]\n\n");

        let mut generated_files: Vec<String> = fs::read_dir(&generated_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|ext| ext == "rs"))
            .filter(|p| p.file_name().unwrap() != "mod.rs")
            .filter_map(|p| p.file_stem().map(|s| s.to_string_lossy().to_string()))
            .collect();
        generated_files.sort();

        for name in &generated_files {
            content.push_str(&format!("pub mod {name};\n"));
        }

        fs::write(&mod_rs, content).unwrap();
    }

    // Tell downstream crates where to find the generated code
    println!(
        "cargo:rustc-env=FLATBUFFERS_GENERATED_DIR={}",
        generated_dir.display()
    );
}

/// Find the fbs/ directory relative to the workspace root.
fn find_fbs_dir() -> PathBuf {
    // Walk up from this build script's directory to find the workspace root
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let mut dir = manifest_dir.as_path();
    loop {
        let fbs = dir.join("fbs");
        if fbs.is_dir() {
            return fbs;
        }
        match dir.parent() {
            Some(parent) => dir = parent,
            None => panic!("Could not find fbs/ directory"),
        }
    }
}

/// Required flatc version (pinned for reproducibility).
const REQUIRED_FLATC_VERSION: &str = "25.12.19";

/// Find the flatc binary and verify version.
fn find_flatc() -> Option<PathBuf> {
    // Check environment variable first
    if let Ok(flatc) = env::var("FLATC") {
        return Some(PathBuf::from(flatc));
    }

    // Check if flatc is on PATH
    if let Ok(output) = Command::new("flatc").arg("--version").output() {
        if output.status.success() {
            let version_str = String::from_utf8_lossy(&output.stdout);
            let version = version_str.trim();
            eprintln!("Using system flatc: {version}");

            // Verify version matches expected
            if !version.contains(REQUIRED_FLATC_VERSION) {
                eprintln!(
                    "WARNING: flatc version mismatch. Expected {REQUIRED_FLATC_VERSION}, \
                     found {version}. Build may produce incompatible code."
                );
            }

            return Some(PathBuf::from("flatc"));
        }
    }

    None
}
