[package]
name = "nexora-persistor-rocksdb"
description = "RocksDB persistence backend for Nexora — hot storage layer"
version.workspace = true
edition.workspace = true

[dependencies]
nexora-id = { path = "../nexora-id" }
nexora-value = { path = "../nexora-value" }
nexora-core = { path = "../nexora-core" }
nexora-serialization = { path = "../nexora-serialization" }
rust-rocksdb = "0.50"
async-trait = "0.1"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
byteorder = { workspace = true }
bincode = "1.3"

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
