apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexora
  namespace: nexora
  labels:
    app.kubernetes.io/name: nexora
    app.kubernetes.io/component: monitoring
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nexora
  namespaceSelector:
    matchNames:
      - nexora
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      scheme: http
      params:
        module: [http_2xx]
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - targetLabel: nexora_cluster
          replacement: nexora
