//! HTML report generation — creates self-contained HTML with inline CSS/JS charts.

use crate::comparison::BenchmarkResult;
use crate::tpc_graph::TpcQueryResult;
use std::fmt::Write;

/// Generate a self-contained HTML report from benchmark results.
pub fn generate_html(
    comparison_results: &[BenchmarkResult],
    tpc_results: &[TpcQueryResult],
) -> String {
    let mut html = String::new();

    html.push_str(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>nexora Benchmark Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117;
    color: #c9d1d9;
    line-height: 1.6;
    padding: 2rem;
  }
  h1 { color: #58a6ff; font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 { color: #79c0ff; font-size: 1.4rem; margin: 2rem 0 1rem; }
  h3 { color: #d2a8ff; font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
  .subtitle { color: #8b949e; margin-bottom: 2rem; }
  .card {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 1rem;
  }
  th, td {
    text-align: left;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid #30363d;
  }
  th { color: #58a6ff; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; }
  td { font-size: 0.9rem; }
  .metric { font-family: 'SF Mono', 'Fira Code', monospace; color: #7ee78b; }
  .bar-chart { margin: 1rem 0; }
  .bar-row { display: flex; align-items: center; margin-bottom: 0.4rem; }
  .bar-label { width: 200px; font-size: 0.85rem; color: #8b949e; }
  .bar-track { flex: 1; background: #21262d; border-radius: 4px; height: 24px; position: relative; }
  .bar-fill {
    height: 100%;
    border-radius: 4px;
    background: linear-gradient(90deg, #238636, #2ea043);
    transition: width 0.5s ease;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    padding-right: 8px;
    font-size: 0.75rem;
    color: #fff;
    min-width: 40px;
  }
  .bar-fill.latency { background: linear-gradient(90deg, #b35900, #d4733a); }
  .bar-fill.p95 { background: linear-gradient(90deg, #8957e5, #bc8cff); }
  .bar-fill.p99 { background: linear-gradient(90deg, #da3633, #f85149); }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
  @media (max-width: 768px) { .grid { grid-template-columns: 1fr; } }
  .stat-box { text-align: center; padding: 1rem; }
  .stat-value { font-size: 1.8rem; font-weight: 700; color: #58a6ff; }
  .stat-label { font-size: 0.8rem; color: #8b949e; text-transform: uppercase; }
  .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>nexora Performance Benchmark Report</h1>
<p class="subtitle">Generated by nexora-bench</p>
"#);

    // Summary stats
    html.push_str("<h2>Summary</h2>\n<div class=\"grid\">\n");
    let total_ops: usize = comparison_results.iter().map(|r| r.operations).sum();
    let avg_throughput: f64 = if comparison_results.is_empty() {
        0.0
    } else {
        comparison_results
            .iter()
            .map(|r| r.throughput_ops_sec)
            .sum::<f64>()
            / comparison_results.len() as f64
    };
    let total_queries: usize = tpc_results.iter().map(|r| r.iterations).sum();

    write!(
        html,
        r#"<div class="card stat-box">
      <div class="stat-value">{}</div><div class="stat-label">Total Operations</div></div>"#,
        format_number(total_ops as f64)
    )
    .unwrap();
    write!(
        html,
        r#"<div class="card stat-box">
      <div class="stat-value">{}</div><div class="stat-label">Avg Throughput (ops/s)</div></div>"#,
        format_number(avg_throughput)
    )
    .unwrap();
    write!(
        html,
        r#"<div class="card stat-box">
      <div class="stat-value">{}</div><div class="stat-label">TPC Queries Run</div></div>"#,
        format_number(total_queries as f64)
    )
    .unwrap();
    write!(
        html,
        r#"<div class="card stat-box">
      <div class="stat-value">{}</div><div class="stat-label">Benchmark Scenarios</div></div>"#,
        comparison_results.len()
    )
    .unwrap();
    html.push_str("</div>\n");

    // Comparison results — throughput chart
    if !comparison_results.is_empty() {
        html.push_str("<h2>CRUD &amp; Traversal — Throughput</h2>\n<div class=\"card\">\n");
        html.push_str("<div class=\"bar-chart\">\n");
        let max_tp = comparison_results
            .iter()
            .map(|r| r.throughput_ops_sec)
            .fold(0.0f64, f64::max);
        for r in comparison_results {
            let pct = (r.throughput_ops_sec / max_tp * 100.0) as u32;
            write!(
                html,
                r#"<div class="bar-row"><div class="bar-label">{} ({})</div><div class="bar-track"><div class="bar-fill" style="width: {}%">{}</div></div></div>"#,
                r.operation,
                format_number(r.operations as f64),
                pct.max(2),
                format_number(r.throughput_ops_sec)
            ).unwrap();
        }
        html.push_str("</div>\n");

        // Latency table
        html.push_str("<h3>Latency Breakdown (microseconds)</h3>\n<table>\n");
        html.push_str("<tr><th>Operation</th><th>Count</th><th>Throughput</th><th>p50</th><th>p95</th><th>p99</th><th>Mean</th></tr>\n");
        for r in comparison_results {
            writeln!(
                html,
                "<tr><td>{}</td><td>{}</td><td class=\"metric\">{}</td><td class=\"metric\">{:.1}</td><td class=\"metric\">{:.1}</td><td class=\"metric\">{:.1}</td><td class=\"metric\">{:.1}</td></tr>",
                r.operation,
                r.operations,
                format_number(r.throughput_ops_sec),
                r.latency.p50_us,
                r.latency.p95_us,
                r.latency.p99_us,
                r.latency.mean_us
            ).unwrap();
        }
        html.push_str("</table>\n</div>\n");
    }

    // TPC results
    if !tpc_results.is_empty() {
        html.push_str("<h2>TPC-H Style Graph Benchmark</h2>\n<div class=\"card\">\n");
        html.push_str("<div class=\"bar-chart\">\n");
        let max_qps = tpc_results
            .iter()
            .map(|r| r.throughput_qps)
            .fold(0.0f64, f64::max);
        for r in tpc_results {
            let pct = (r.throughput_qps / max_qps * 100.0) as u32;
            write!(
                html,
                r#"<div class="bar-row"><div class="bar-label">{} ({})</div><div class="bar-track"><div class="bar-fill" style="width: {}%">{}</div></div></div>"#,
                r.query_name,
                r.scale_factor,
                pct.max(2),
                format_number(r.throughput_qps)
            ).unwrap();
        }
        html.push_str("</div>\n");

        // TPC latency table
        html.push_str("<h3>TPC Query Latency (microseconds)</h3>\n<table>\n");
        html.push_str("<tr><th>Query</th><th>Scale</th><th>Iterations</th><th>QPS</th><th>p50</th><th>p95</th><th>p99</th><th>Result Size</th></tr>\n");
        for r in tpc_results {
            writeln!(
                html,
                "<tr><td>{}</td><td>{}</td><td>{}</td><td class=\"metric\">{}</td><td class=\"metric\">{:.1}</td><td class=\"metric\">{:.1}</td><td class=\"metric\">{:.1}</td><td>{}</td></tr>",
                r.query_name,
                r.scale_factor,
                r.iterations,
                format_number(r.throughput_qps),
                r.latency.p50_us,
                r.latency.p95_us,
                r.latency.p99_us,
                r.result_size
            ).unwrap();
        }
        html.push_str("</table>\n</div>\n");

        // p95/p99 comparison chart
        html.push_str(
            "<h3>p95 Latency Comparison</h3>\n<div class=\"card\">\n<div class=\"bar-chart\">\n",
        );
        let max_p95 = tpc_results
            .iter()
            .map(|r| r.latency.p95_us)
            .fold(0.0f64, f64::max);
        for r in tpc_results {
            let pct = (r.latency.p95_us / max_p95 * 100.0) as u32;
            write!(
                html,
                r#"<div class="bar-row"><div class="bar-label">{}</div><div class="bar-track"><div class="bar-fill p95" style="width: {}%">{:.0}s</div></div></div>"#,
                r.query_name,
                pct.max(2),
                r.latency.p95_us
            ).unwrap();
        }
        html.push_str("</div>\n</div>\n");
    }

    // Footer
    html.push_str("<div class=\"footer\">\n");
    html.push_str("Generated by nexora-bench | nexora graph database benchmark suite\n");
    html.push_str("</div>\n</body>\n</html>\n");

    html
}

fn format_number(n: f64) -> String {
    if n >= 1_000_000.0 {
        format!("{:.1}M", n / 1_000_000.0)
    } else if n >= 1_000.0 {
        format!("{:.1}K", n / 1_000.0)
    } else {
        format!("{:.0}", n)
    }
}
