apiVersion: 1
providers:
  - name: 'DeepStreaming'
    folder: 'StreamingGraph'
    options:
      path: /etc/grafana/provisioning/dashboards
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
