#!/usr/bin/env python3
"""
Generate a Markdown benchmark report from Criterion results and comparison JSON.

Usage:
    python3 generate_report.py \
        --criterion-dir target/criterion \
        --comparison-json target/comparison_results.json \
        --output target/bench-reports/benchmark_report.md
"""

import argparse
import json
import os
import sys
from pathlib import Path


def format_duration(ns: float) -> str:
    """Format nanoseconds into a human-readable duration string."""
    if ns < 1_000:
        return f"{ns:.0f} ns"
    elif ns < 1_000_000:
        return f"{ns / 1_000:.2f} us"
    elif ns < 1_000_000_000:
        return f"{ns / 1_000_000:.2f} ms"
    else:
        return f"{ns / 1_000_000_000:.3f} s"


def format_throughput(ops_per_sec: float) -> str:
    """Format throughput into a human-readable string."""
    if ops_per_sec >= 1_000_000:
        return f"{ops_per_sec / 1_000_000:.2f} M ops/s"
    elif ops_per_sec >= 1_000:
        return f"{ops_per_sec / 1_000:.2f} K ops/s"
    else:
        return f"{ops_per_sec:.1f} ops/s"


def parse_criterion_results(criterion_dir: Path) -> list[dict]:
    """Parse all estimates.json files from Criterion output."""
    results = []
    if not criterion_dir.exists():
        return results

    for group_dir in sorted(criterion_dir.iterdir()):
        if not group_dir.is_dir():
            continue
        group_name = group_dir.name

        for bench_dir in sorted(group_dir.iterdir()):
            if not bench_dir.is_dir():
                continue
            bench_name = bench_dir.name

            estimates_file = bench_dir / "new" / "estimates.json"
            if not estimates_file.exists():
                continue

            try:
                with open(estimates_file) as f:
                    data = json.load(f)
            except (json.JSONDecodeError, IOError):
                continue

            mean_ns = data.get("mean", {}).get("point_estimate", 0)
            median_ns = data.get("median", {}).get("point_estimate", 0)
            p99 = data.get("median", {}).get("point_estimate", 0)

            # Try to get p99 from slope or confidence interval
            ci = data.get("mean", {}).get("confidence_interval", {})
            if ci:
                upper = ci.get("upper_bound", mean_ns)
                p99 = upper

            results.append({
                "group": group_name,
                "benchmark": bench_name,
                "mean_ns": mean_ns,
                "median_ns": median_ns,
                "p99_ns": p99,
            })

    return results


def parse_comparison_json(comparison_path: Path) -> list[dict]:
    """Parse comparison_results.json."""
    if not comparison_path.exists():
        return []
    try:
        with open(comparison_path) as f:
            data = json.load(f)
    except (json.JSONDecodeError, IOError):
        return []
    return data.get("results", [])


def generate_report(criterion_results, comparison_results) -> str:
    """Generate the Markdown report."""
    lines = []
    lines.append("# nexora Benchmark Report")
    lines.append("")
    lines.append(f"> Auto-generated by `benches/run_benchmarks.sh`")
    lines.append("")

    # --- Criterion Results ---
    if criterion_results:
        lines.append("## Criterion Benchmark Results")
        lines.append("")
        lines.append("| Group | Benchmark | Mean | Median | P99 (est) |")
        lines.append("|-------|-----------|------|--------|-----------|")
        for r in criterion_results:
            lines.append(
                f"| {r['group']} | {r['benchmark']} "
                f"| {format_duration(r['mean_ns'])} "
                f"| {format_duration(r['median_ns'])} "
                f"| {format_duration(r['p99_ns'])} |"
            )
        lines.append("")

    # --- Comparison Results ---
    if comparison_results:
        lines.append("## Comparison Framework Results")
        lines.append("")
        lines.append("JSON file: `target/comparison_results.json`")
        lines.append("")
        lines.append("| Operation | P50 | P99 | Mean | Throughput | Total Ops |")
        lines.append("|-----------|-----|-----|------|------------|-----------|")
        for r in comparison_results:
            p50 = r.get("latency_p50_ns", 0)
            p99 = r.get("latency_p99_ns", 0)
            mean = r.get("latency_mean_ns", 0)
            tput = r.get("throughput_ops_per_sec", 0)
            ops = r.get("total_ops", 0)
            lines.append(
                f"| {r['operation']} "
                f"| {format_duration(p50)} "
                f"| {format_duration(p99)} "
                f"| {format_duration(mean)} "
                f"| {format_throughput(tput)} "
                f"| {ops} |"
            )
        lines.append("")

    # --- Comparison JSON (raw, for cross-database comparison) ---
    if comparison_results:
        lines.append("## Raw JSON Output")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps({"results": comparison_results}, indent=2))
        lines.append("```")
        lines.append("")

    if not criterion_results and not comparison_results:
        lines.append("_No benchmark results found._")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("**Notes:**")
    lines.append("- Times are wall-clock measurements; async overhead is included.")
    lines.append("- P99 estimates from Criterion are upper confidence bounds.")
    lines.append("- Comparison JSON can be used for side-by-side comparison with Neo4j/ArangoDB.")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Markdown benchmark report"
    )
    parser.add_argument(
        "--criterion-dir",
        type=Path,
        default=Path("target/criterion"),
        help="Path to Criterion output directory",
    )
    parser.add_argument(
        "--comparison-json",
        type=Path,
        default=Path("target/comparison_results.json"),
        help="Path to comparison_results.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("target/bench-reports/benchmark_report.md"),
        help="Output Markdown file path",
    )
    args = parser.parse_args()

    criterion_results = parse_criterion_results(args.criterion_dir)
    comparison_results = parse_comparison_json(args.comparison_json)

    report = generate_report(criterion_results, comparison_results)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report)

    print(f"Report written to {args.output}")
    print(f"  - {len(criterion_results)} criterion results")
    print(f"  - {len(comparison_results)} comparison results")


if __name__ == "__main__":
    main()
